Load minimal ruleset first, so there's a baseline in case the main rules fail
git-svn-id: http://kaini.schwarzvogel.de/svn/repos/fina/trunk@43 bbab99c9-e8d4-40e5-953a-fbd5b2b2805b

diff --git a/fina.init b/fina.init
--- a/fina.init
+++ b/fina.init
@@ -38,6 +38,18 @@ start_fina()
   fi
 }
 
+load_minimal()
+{
+  echo -n "Loading minimal ruleset..."
+  MSG=$("$DAEMON" -m 2>&1)
+  RETVAL=$?
+  if [[ $RETVAL != 0 ]]; then
+    echo "failed ($MSG)" >&2
+  else
+    echo "ok"
+  fi
+}
+
 stop_fina()
 {
   echo "There is no stop action for fina because there is no clear" >&2
@@ -52,11 +64,15 @@ case "$1" in
     ;;
   stop)
     stop_fina
-    exit 1
+    exit 0
     ;;
   restart)
     echo -n "Restarting fina: "
     start_fina
+    ;;
+  minimal)
+    echo -n "Loading minimal ruleset: "
+    load_minimal
     ;;
   *)
     echo "Usage: $0 {start|stop|restart}"
